[[dev-guide-build-entitlements]]
= Build Entitlements
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

[[managing-entitlements-rhel-docker-formatted-builds]]
== Managing Entitlements For RHEL Docker-Formatted Builds

When planning a build of a RHEL based docker-formatted container that includes a package requiring a subscription (or "entitlement") not enabled on the build host, a deeper understanding of how subscriptions are inherited from the build host is needed to ensure a successful build.

The host that will be used to build a docker-formatted container will need to be subscribed to all repositories required during the build by using Red Hat Subscription Manager. During the build, a docker-formatted container will have access to the same subscriptions as the host through the use of the xref:secrets-patch[secrets patch]. The xref:secrets-patch[secrets patch] allows docker-formatted container images that are built on the host to enable *any* repository provided by the host's entitlements regardless of whether or not the repositories are enabled on the host. The reason for this relationship between the build environment for a docker-formatted container and host is because subscription-manager sub-commands are not available inside docker-formatted container images.

You can get a complete list of which subscriptions will be available to the docker-formatted container during a build by running:

[source, bash]
----
[root@docker_host ~]# subscription-manager repos --list
----

[NOTE]
====
This command is run on the docker host system.
====

Any repository enabled by the host can be seen by the container automatically. Repositories do not explicitly need to be enabled on the host for containers to use them, the host system need only provide entitlements that have access to the repositories.

[[secrets-patch]]
== Understanding The Secrets Patch

To understand how docker-formatted containers are able to use any entitlements available to the host, a closer look at the secrets patch is needed.

On the build host, the files needed for Red Hat Subscription Management (RHSM) are linked from the *secrets* directory:

[source, bash]
----
$ ls -l /usr/share/rhel/secrets/
lrwxrwxrwx. 1 root root 20 etc-pki-entitlement -> /etc/pki/entitlement
lrwxrwxrwx. 1 root root 28 rhel7.repo -> /etc/yum.repos.d/redhat.repo
lrwxrwxrwx. 1 root root  9 rhsm -> /etc/rhsm
----

When a docker-formatted container build is started, the host directory *_/usr/share/rhel/secrets_* is mounted at *_/run/secrets_*:

[source, bash]
----
[c0725d5ddf52 /]# ls -l /run/secrets/
total 344
drwx------. 2 root root    138 etc-pki-entitlement
-rwx------. 1 root root 349446 rhel7.repo
drwx------. 4 root root     73 rhsm
----

[NOTE]
====
Currently docker-formatted containerized environment supports this functionality only via Red Hat Subscription Manager (RHSM). Docker containerized environment does not support the use of Red Hat Update Infrastructure (RHUI).
====

When a docker-formatted container build is first started, the contents of *_/etc/yum.repos.d/redhat.repo_* inside the container are blank. It is only when the first `yum` command is issued that a docker-formatted container specific *_subscription-manager_* plugin contacts the RHSM network and provides entitlement information from the host (using the entitlement and RHSM information mounted in *_/run/secrets_*) to the container and uses the output to populate the *_/etc/yum.repos.d/redhat.repo_* file.

For more information on the background on the RHEL specific "super-secrets" patch see the  link:https://github.com/projectatomic/docker/tree/docker-1.13.1-rhel#add-rhel-super-secrets-patchpatch[Project Atomic Release Notes for Docker]

[[building-rhel-6-containers-on-rhel-7]]
=== Building RHEL 6 containers on RHEL 7 build hosts

Since the *_/etc/yum.repos.d/redhat.repo_* file isn't populated until the first yum command, entitlements for RHEL 6 content is available to a RHEL 6 docker-formatted container as long as the entitlements for the RHEL 7 host also have permission for RHEL 6 content. This special functionality is what enables builds of RHEL 6 docker-formatted container on a RHEL 7 build host with no additional requirements.

////
ifdef::openshift-enterprise[]
////
[discrete]
[[entitlement-management-for-multi-tenancy]]
=== Entitlement Management For Multi-Tenancy

For managing entitlements when migrating or upgrading build hosts, either within a cluster or in blue/green deployments, see the section on link:https://docs.openshift.com/container-platform/3.6/install_config/upgrading/blue_green_deployments.html#blue-green-deployments-preparing-for-upgrade[Blue-Green Deployments]
////
endif::openshift-enterprise[]
////
